### PR TITLE
[Don't merge] Java SDK For new version 2018-01-31

### PR DESCRIPTION
**Pull request by kjeur**
Updating SDK for new verssion 2018-01-31

Reference
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/consumption/resource-manager/readme.md#java

### CODE REVIEW

**Comment by milismsft** [comment]
Can you please include in your PR an update to the api-specs.json which is used to generated the Java inner classes?

**Comment by anuchandy** [comment]
@kjeur thanks for the PR. Can you please send a new PR with a clean commit? it seems there is a commit in this PR with some python files deleted. We are trying to have a clean commit history in the repo.

**Comment by anuchandy** [comment]
@kjeur what I mean is:

0. If your local clone is corrupted, just create a new clone in a different dir
1. `git remote add upstream git@github.com:Azure/azure-libraries-for-java.git`
2. `git pull upstream master`
3. `git checkout -b consumption-2018-01 upstream/master`
4. update the `api-spec.json` to refer new spec
```json
  "consumption": {
    "dir": "azure-mgmt-consumption",
    "source": "specification/consumption/resource-manager/readme.md",
    "package": "com.microsoft.azure.management.consumption",
    "args": "--payload-flattening-threshold=1 --tag=package-2018-01"
  },
```
5. commit this file with comment `updating consumption entry to refer package-2018-01`
6. `npm install --global`
7. `gulp codegen --projects consumption`
8. Add the generated files (`git add -A`) and create a commit `git commit -m "regenerating consumption from package-2018-01"`
9. `git push origin consumption-2018-01`
10. send a PR from your fork.

**Comment by kjeur** [comment]
@anuchandy closing this PR. I'll create new with commit messages as suggested.

**Pull request closed without merging**
