### PR TITLE
Only trigger pr that merged to master

### PR DESCRIPTION
**Pull request by ChenTanyi**

### CODE REVIEW

**Comment by ChenTanyi** [comment]
Since the previous PR didn't merge, it run my pipeline wrongly, I have disabled it first and I think I could only create a new PR.

**Comment by ChenTanyi** [comment]
@yungezz We should set the first CI as not required currently, as it should run in vnext branch rather than master, but currently the vnext ci have not been merged.

**Comment by yungezz** [comment]
> @yungezz We should set the first CI as not required currently, as it should run in vnext branch rather than master, but currently the vnext ci have not been merged.

will sync with  you offline

**Pull request closed without merging**
