### PR TITLE
force deletion on resource group

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
https://github.com/Azure/azure-libraries-for-java/pull/1354/commits/a91bf8a83c6cebb815455f890968e08ab42c5ee2 is the code change.

### CODE REVIEW

**Review by xccc-msft — APPROVED** [review]
Have this been tested on local?

**Comment by weidongxu-microsoft** [comment]
> Have this been tested on local?

Yes, but no way to tell whether it is "force" or now, just see the query parameter is on url.

**Comment by xccc-msft** [comment]
> > Have this been tested on local?
> 
> Yes, but no way to tell whether it is "force" or now, just see the query parameter is on url.

Not sure if it gets supported all regions now. For compute force delete, it could throw errors when testing on unsupported regions.

**Comment by weidongxu-microsoft** [comment]
> > > Have this been tested on local?
> > 
> > 
> > Yes, but no way to tell whether it is "force" or now, just see the query parameter is on url.
> 
> Not sure if it gets supported all regions now. For compute force delete, it could throw errors when testing on unsupported regions.

Yes, I saw that on VM delete.

But apparently this cannot be for resource group delete. This need to be successful, regardless force or not, EUAP or not. (delete is success on normal region)

**Pull request merged**
