### PR TITLE
Update pom.xml and put a more obvious message

### PR DESCRIPTION
**Pull request by nickzhums**

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by ChenTanyi** [comment]
Might be better to change all pom, like https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-resources/pom.xml#L19

**Comment by nickzhums** [comment]
could you mege the PR ? I don't  have permission @weidongxu-microsoft  thanks!

**Comment by nickzhums** [comment]
> Might be better to change all pom, like https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-resources/pom.xml#L19

hmm good point, is there a quick way to do this?

**Comment by ChenTanyi** [comment]
@nickzhums You can do text replacement, I think all messages are same among all pom.

**Pull request merged**
