### PR TITLE
Private dns sample

### PR DESCRIPTION
**Pull request by lmazuel**

### CODE REVIEW

**Comment by praries880** [comment]
@lmazuel , @ovidiu10  need to fix the style check issues : https://dev.azure.com/azure-sdk/public/_build/results?buildId=65861&view=logs&j=572c5e49-83d5-5271-390a-e6dc77f89c6b&t=adfb0d43-1aa5-5c96-97ee-07f6c8a11e41&l=17

**Comment by ovidiu10** [comment]
I’ll check Thanks

**Comment by ovidiu10** [comment]
fixed please try again

**Comment by ovidiu10** [comment]
finally :) just travis-ci throw an error

**Pull request merged**
